name: Random Joke
author: Ali Alaa
#description: "Generate a random joke and send it to slack"
description: "Generate a random joke, save to file and upload as artefact"
inputs:
#  slack_username:
#    description: "Slack Username"
  upload_joke:
    description: "Upload Joke as an Artifact?"
#  slack_webhook:
#    description: "Slack Webhook"
outputs:
  joke:
    description: The generatred joke
    value: ${{ steps.joke.outputs.random_joke }}
runs:
  using: composite
  steps:
    - name: Generate Joke
      shell: bash
      id: joke
      # This allows you to send multi-line content into OUTPUT using delimiters
      run: |
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "random_joke<<$EOF" >> "$GITHUB_OUTPUT"
        curl -s https://icanhazdadjoke.com/ >> "$GITHUB_OUTPUT"
        echo "" >> "$GITHUB_OUTPUT"
        echo "$EOF" >> "$GITHUB_OUTPUT"
    - name: Generate Joke File
      shell: bash
      run: echo '${{ steps.joke.outputs.random_joke }}' > joke.txt
      if: inputs.upload_joke
    - name: Upload the Joke
      if: inputs.upload_joke
      uses: actions/upload-artifact@v3
      with:
        name: joke
        path: joke.txt