name: Caching and Artefacts
on: [workflow_dispatch]
jobs:
  use-axios:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3

        # use a standard action to cache npm dependencies 
        # note there are re-defined actions for node, java etc set up
        # which have caching pre-integrated. But this is how you can do it
        # manually if required for other package managers
        - name: cache node modules
          id: cache-dependencies
          uses: actions/cache@v3
          with:
            path: ~/.npm
            key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              ${{ runner.os }}-npm-cache-

        # display the cache output 
        - name: Display cache output
          run: echo '${{ toJson(steps.cache-dependencies.outputs) }}'

        # install npm dependencies 
        - name: Install dependencies
          run: npm install

        # run tests - in this case uses jest as defined in package.json
        - name: Run Tests
          run: npm test

        # use a standard action to upload generated artifacts
        - name: Upload Code Coverage Report
          uses: actions/upload-artifact@v3
          if: always()
          with:
            name: code-coverage
            path: coverage
            retention-days: 10

        - name: Download Code Coverage
          uses: actions/download-artifact@v3
          with:
            name: code-coverage
            path: code-coverage-report
        - run: ls -a
        - run: ls -a
          working-directory: code-coverage-report

        - name: Use Axios
          uses: actions/github-script@v6
          with:
            script: |
              const axios = require('axios');
              const res = await axios('https://icanhazdadjoke.com/', { headers: { Accept: 'text/plain' } })
              console.log(res.data)