name: Docker
on: [workflow_dispatch]

jobs:
    docker-job:
        runs-on: ubuntu-latest
        # pulls from docker hub - https://hub.docker.com/_/node
        # select an up-to-date image tag
        container: 
            image: node:22-alpine3.19
        env:
            API_URL: some-url.com

        #ports:
        #    - 80
#        volumes:
#    - vol_name:/path/in/container
#            - /path/to/container
#            - /path/in/host
                
        steps:
            - name: Log Node & OS Versions
              run: |
                node -v
                cat /etc/os-release
            - name: Log Env
              run: echo $API_URL
            - name: Create a file
              run: echo 'some text' > text.txt

            - name: Container in a Step
              uses: docker://node:20.14-alpine3.19
              with:
                # overwrites ENTRYPOINT in Dockerfile
                entrypoint: /usr/local/bin/node
                # overwrites CMD in Dockerfile
                args: -p 2+3

            - name: Log node version
              uses: docker://node:20.14-alpine3.19
              with:
                # overwrites CMD in Dockerfile
                args: -v
                
            - name: show file contents
              uses: docker://node:18.20-alpine3.19
              with:
                entrypoint: cat
                args: text.txt