name: Manually Triggered

on:
    workflow_dispatch:
        inputs:
            string:
                description: A string input
                type: string
                required: true
                default: "default value"
            environment:
                description: "Enviroment"
                type: environment
                required: true

jobs:
    log-info:
        runs-on: ubuntu-latest
        steps:
            - run: echo $GITHUB_REF
            - run: |
                echo "String: ${{ inputs.string }}"
                echo "Environment: ${{ inputs.environment }}"
                