name: Reusable Workflow
on:
  workflow_call:
    outputs:
        date: 
            description: "date value"
            value: ${{ jobs.generate-output.outputs.date }}

jobs:
  nested-workflow-call:
    uses: n-jc-org/udemy-GHA-course-2/.github/workflows/reusable.yaml@main
    with:
      name: "Nathan"
    secrets:
      access-token: ${{ secrets.ACCESS_TOKEN }}

  generate-output:
    runs-on: ubuntu-latest
    outputs:
        date: ${{ steps.date-step.outputs.date }}
    steps:
        - run: echo "date=$(date)" >> $GITHUB_OUTPUT
          id: date-step