name: Status CHeck Functions
on: [push]

jobs:
    job-1:
        runs-on: ubuntu-latest
        timeout-minutes: 1
        steps:
            - name: Step 1
              run: sleep 90
              # timeout-minutes: 1
            - name: Step 2
              id: step-2
              continue-on-error: true
              run: exit 1
            - name: Runs on step2 failure
              if: failure() && steps.step-2.conclusion == 'failure'
              run: echo 'step 2 has failed'
            - name: Runs on failure
              if: failure() 
              run: echo 'Failure'
            - name: Runs on Success
            # this is not needed as default behavior
              if: success()
              run: echo 'Runs of Success'
            - name: Always Runs
              # same as if success() || failure()
              if: always()
              run: echo 'Always runs'
            - name: Runs when cancelled
              if: cancelled()
              run: echo 'Run on cancelled'  
    job-2:
        runs-on: ubuntu-latest
        needs: job-1
        if: failure()
        steps:
            - run: echo 'Job 2 runs becuase job 1 failed'