name: Status CHeck Functions
on: [push]

jobs:
    job-1:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1
              run: sleep 20
            - name: Runs on failure
              if: failure()
              run: echo 'runs Only on failure'
            - name: Runson Success
            # this is not needed as default behavior
              if: success()
              run: echo 'Runs of Success'
            - name: Always Runs
              # same as if success() || failure()
              if: always()
              run: echo 'Always runs'
            - name: Runs when cancelled
              if: cancelled()
              run: echo 'Rund on cancelled'  
    job-2:
        runs-on: ubuntu-latest
        name: job-1
        if: failure()