name: Calling reusable workflows

on:
    workflow_dispatch:
        inputs:
            name:
                description: "input description"
                type: string
                default: "Ali"
                required: false

jobs:
    calling-a-resuable-wf:
        uses: n-jc-org/udemy-GHA-course-2/.github/workflows/reusable.yaml@main
        with:
            name: ${{ inputs.name }}
        secrets:
            access-token: ${{ secrets.ACCESS_TOKEN}}