name: Workflow Run

on:
    workflow_run:
        workflows: [Repo Events]
        types: [completed]

jobs:
    echo-string:
        runs-on: ununtu-latest
        steps:
            - run: echo "Hey, I was triggered because 'Repo Events' was completed"